name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependecies
        run: |
          yarn

      - name: Lint
        run: |
          yarn lint

      - name: Test
        run: |
          yarn test
        env:
          INVITATIONS_SENDGRID_API_KEY: INVITATIONS_SENDGRID_API_KEY
          INVITATIONS_SENDGRID_TEMPLATE_ID: INVITATIONS_SENDGRID_TEMPLATE_ID
          INVITATIONS_LINK_PREFIX: http://localhost:3001/invite
          INVITATIONS_FROM_EMAIL: vladimir.osipov@8base.com
